name: Build and deploy - Front-end Telemetry 

on:
  push:
    branches:
      - develop
    paths:
      - frontend/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './frontend'

    steps:
      
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.1
        
      - name: Install Yarn
        run: npm install -g yarn
        
      - name: yarn install, build
        run: |
          yarn
          yarn build
