name: Build and deploy - Front-end Telemetry 

on:
  push:
    branches:
      - dev
    paths:
      - frontend/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './frontend'

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
            node-version: 18

      - name: yarn install dependencies and build
        run: |
          yarn
          yarn build